version: '2'
services:
  db:
    image: mysql
    container_name: symfony_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "80:80"
    volumes_from:
      - php
    volumes:
      - ./etc/build/dev/nginx/conf.d:/etc/nginx/conf.d
      - ./var/logs/nginx:/var/log/nginx

  php:
    image: letsbonus/php-dev:7.0
    container_name: symfony_php
    links:
      - db
    volumes:
      - ./:/app
    ports:
      - "2222:22"
    working_dir: /app
